name: Test environments

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment'

jobs:
  some-job:
    name: Export tables
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment name
        shell: 'script -q -e -c "bash {0}"'
        run: |
            echo "Environment in use: ${{vars.ENV}}"

